export const supportedCountries = [
        { ID: 1, abbrev: 'ABW', country: 'Aruba' },
        { ID: 2, abbrev: 'AFG', country: 'Afghanistan' },
        { ID: 3, abbrev: 'AGO', country: 'Angola' },
        { ID: 4, abbrev: 'AIA', country: 'Anguilla' },
        { ID: 6, abbrev: 'ALA', country: 'Aland Islands' },
        { ID: 5, abbrev: 'ALB', country: 'Albania' },
        { ID: 7, abbrev: 'AND', country: 'Andorra' },
        { ID: 8, abbrev: 'ARE', country: 'United Arab Emirates' },
        { ID: 9, abbrev: 'ARG', country: 'Argentina' },
        { ID: 10, abbrev: 'ARM', country: 'Armenia' },
        { ID: 11, abbrev: 'ASM', country: 'American Samoa' },
        { ID: 12, abbrev: 'ATA', country: 'Antarctica' },
        { ID: 13, abbrev: 'ATF', country: 'French Southern and Antarctic Lands' },
        { ID: 14, abbrev: 'ATG', country: 'Antigua and Barbuda' },
        { ID: 15, abbrev: 'AUS', country: 'Australia' },
        { ID: 16, abbrev: 'AUT', country: 'Austria' },
        { ID: 17, abbrev: 'AZE', country: 'Azerbaijan' },
        { ID: 18, abbrev: 'BDI', country: 'Burundi' },
        { ID: 19, abbrev: 'BEL', country: 'Belgium' },
        { ID: 20, abbrev: 'BEN', country: 'Benin' },
        { ID: 21, abbrev: 'BFA', country: 'Burkina Faso' },
        { ID: 22, abbrev: 'BGD', country: 'Bangladesh' },
        { ID: 23, abbrev: 'BGR', country: 'Bulgaria' },
        { ID: 24, abbrev: 'BHR', country: 'Bahrain' },
        { ID: 25, abbrev: 'BHS', country: 'Bahamas' },
        { ID: 26, abbrev: 'BIH', country: 'Bosnia and Herzegovina' },
        { ID: 27, abbrev: 'BLM', country: 'Saint-Barthelemy' },
        { ID: 28, abbrev: 'BLR', country: 'Belarus' },
        { ID: 29, abbrev: 'BLZ', country: 'Belize' },
        { ID: 30, abbrev: 'BMU', country: 'Bermuda' },
        { ID: 31, abbrev: 'BOL', country: 'Bolivia' },
        { ID: 32, abbrev: 'BRA', country: 'Brazil' },
        { ID: 33, abbrev: 'BRB', country: 'Barbados' },
        { ID: 34, abbrev: 'BRN', country: 'Brunei Darussalam' },
        { ID: 35, abbrev: 'BTN', country: 'Bhutan' },
        { ID: 36, abbrev: 'BWA', country: 'Botswana' },
        { ID: 37, abbrev: 'CAF', country: 'Central African Republic' },
        { ID: 38, abbrev: 'CAN', country: 'Canada' },
        { ID: 39, abbrev: 'CHE', country: 'Switzerland' },
        { ID: 40, abbrev: 'CHL', country: 'Chile' },
        { ID: 41, abbrev: 'CHN', country: 'China' },
        { ID: 42, abbrev: 'CIV', country: 'Cote d\'Ivoire' },
        { ID: 43, abbrev: 'CMR', country: 'Cameroon' },
        { ID: 44, abbrev: 'COD', country: 'Democratic Republic of the Congo' },
        { ID: 45, abbrev: 'COG', country: 'Republic of Congo' },
        { ID: 46, abbrev: 'COK', country: 'Cook Islands' },
        { ID: 47, abbrev: 'COL', country: 'Colombia' },
        { ID: 48, abbrev: 'COM', country: 'Comoros' },
        { ID: 49, abbrev: 'CPV', country: 'Cape Verde' },
        { ID: 50, abbrev: 'CRI', country: 'Costa Rica' },
        { ID: 51, abbrev: 'CUB', country: 'Cuba' },
        { ID: 52, abbrev: 'CUW', country: 'Curacao' },
        { ID: 53, abbrev: 'CYM', country: 'Cayman Islands' },
        { ID: 54, abbrev: 'CYP', country: 'Cyprus' },
        { ID: 55, abbrev: 'CZE', country: 'Czech Republic' },
        { ID: 56, abbrev: 'DEU', country: 'Germany' },
        { ID: 57, abbrev: 'DJI', country: 'Djibouti' },
        { ID: 58, abbrev: 'DMA', country: 'Dominica' },
        { ID: 59, abbrev: 'DNK', country: 'Denmark' },
        { ID: 60, abbrev: 'DOM', country: 'Dominican Republic' },
        { ID: 61, abbrev: 'DZA', country: 'Algeria' },
        { ID: 62, abbrev: 'ECU', country: 'Ecuador' },
        { ID: 63, abbrev: 'EGY', country: 'Egypt' },
        { ID: 64, abbrev: 'ERI', country: 'Eritrea' },
        { ID: 65, abbrev: 'ESP', country: 'Spain' },
        { ID: 66, abbrev: 'EST', country: 'Estonia' },
        { ID: 67, abbrev: 'ETH', country: 'Ethiopia' },
        { ID: 68, abbrev: 'FIN', country: 'Finland' },
        { ID: 69, abbrev: 'FJI', country: 'Fiji' },
        { ID: 70, abbrev: 'FLK', country: 'Falkland Islands' },
        { ID: 239, abbrev: 'FRA', country: 'France' },
        { ID: 71, abbrev: 'FRO', country: 'Faeroe Islands' },
        { ID: 72, abbrev: 'FSM', country: 'Federated States of Micronesia' },
        { ID: 73, abbrev: 'GAB', country: 'Gabon' },
        { ID: 74, abbrev: 'GBR', country: 'United Kingdom' },
        { ID: 75, abbrev: 'GEO', country: 'Georgia' },
        { ID: 76, abbrev: 'GGY', country: 'Guernsey' },
        { ID: 77, abbrev: 'GHA', country: 'Ghana' },
        { ID: 78, abbrev: 'GIB', country: 'Gibraltar' },
        { ID: 79, abbrev: 'GIN', country: 'Guinea' },
        { ID: 240, abbrev: 'GLP', country: 'Guadeloupe' },
        { ID: 80, abbrev: 'GMB', country: 'The Gambia' },
        { ID: 81, abbrev: 'GNB', country: 'Guinea-Bissau' },
        { ID: 82, abbrev: 'GNQ', country: 'Equatorial Guinea' },
        { ID: 83, abbrev: 'GRC', country: 'Greece' },
        { ID: 84, abbrev: 'GRD', country: 'Grenada' },
        { ID: 85, abbrev: 'GRL', country: 'Greenland' },
        { ID: 86, abbrev: 'GTM', country: 'Guatemala' },
        { ID: 241, abbrev: 'GUF', country: 'French Guiana' },
        { ID: 87, abbrev: 'GUM', country: 'Guam' },
        { ID: 88, abbrev: 'GUY', country: 'Guyana' },
        { ID: 89, abbrev: 'HKG', country: 'Hong Kong' },
        { ID: 90, abbrev: 'HMD', country: 'Heard I. and McDonald Islands' },
        { ID: 91, abbrev: 'HND', country: 'Honduras' },
        { ID: 92, abbrev: 'HRV', country: 'Croatia' },
        { ID: 93, abbrev: 'HTI', country: 'Haiti' },
        { ID: 94, abbrev: 'HUN', country: 'Hungary' },
        { ID: 95, abbrev: 'IDN', country: 'Indonesia' },
        { ID: 96, abbrev: 'IMN', country: 'Isle of Man' },
        { ID: 97, abbrev: 'IND', country: 'India' },
        { ID: 98, abbrev: 'IOT', country: 'British Indian Ocean Territory' },
        { ID: 99, abbrev: 'IRL', country: 'Ireland' },
        { ID: 100, abbrev: 'IRN', country: 'Iran' },
        { ID: 101, abbrev: 'IRQ', country: 'Iraq' },
        { ID: 102, abbrev: 'ISL', country: 'Iceland' },
        { ID: 103, abbrev: 'ISR', country: 'Israel' },
        { ID: 104, abbrev: 'ITA', country: 'Italy' },
        { ID: 105, abbrev: 'JAM', country: 'Jamaica' },
        { ID: 106, abbrev: 'JEY', country: 'Jersey' },
        { ID: 107, abbrev: 'JOR', country: 'Jordan' },
        { ID: 108, abbrev: 'JPN', country: 'Japan' },
        { ID: 109, abbrev: 'KAZ', country: 'Kazakhstan' },
        { ID: 110, abbrev: 'KEN', country: 'Kenya' },
        { ID: 111, abbrev: 'KGZ', country: 'Kyrgyzstan' },
        { ID: 112, abbrev: 'KHM', country: 'Cambodia' },
        { ID: 113, abbrev: 'KIR', country: 'Kiribati' },
        { ID: 114, abbrev: 'KNA', country: 'Saint Kitts and Nevis' },
        { ID: 115, abbrev: 'KOR', country: 'Republic of Korea' },
        { ID: 116, abbrev: 'KOS', country: 'Kosovo' },
        { ID: 117, abbrev: 'KWT', country: 'Kuwait' },
        { ID: 118, abbrev: 'LAO', country: 'Lao PDR' },
        { ID: 119, abbrev: 'LBN', country: 'Lebanon' },
        { ID: 120, abbrev: 'LBR', country: 'Liberia' },
        { ID: 121, abbrev: 'LBY', country: 'Libya' },
        { ID: 122, abbrev: 'LCA', country: 'Saint Lucia' },
        { ID: 123, abbrev: 'LIE', country: 'Liechtenstein' },
        { ID: 124, abbrev: 'LKA', country: 'Sri Lanka' },
        { ID: 125, abbrev: 'LSO', country: 'Lesotho' },
        { ID: 126, abbrev: 'LTU', country: 'Lithuania' },
        { ID: 127, abbrev: 'LUX', country: 'Luxembourg' },
        { ID: 128, abbrev: 'LVA', country: 'Latvia' },
        { ID: 129, abbrev: 'MAC', country: 'Macao' },
        { ID: 130, abbrev: 'MAF', country: 'Saint-Martin' },
        { ID: 131, abbrev: 'MAR', country: 'Morocco' },
        { ID: 132, abbrev: 'MCO', country: 'Monaco' },
        { ID: 133, abbrev: 'MDA', country: 'Moldova' },
        { ID: 134, abbrev: 'MDG', country: 'Madagascar' },
        { ID: 135, abbrev: 'MDV', country: 'Maldives' },
        { ID: 136, abbrev: 'MEX', country: 'Mexico' },
        { ID: 137, abbrev: 'MHL', country: 'Marshall Islands' },
        { ID: 138, abbrev: 'MKD', country: 'Macedonia, Former Yugoslav Republic of' },
        { ID: 139, abbrev: 'MLI', country: 'Mali' },
        { ID: 140, abbrev: 'MLT', country: 'Malta' },
        { ID: 141, abbrev: 'MMR', country: 'Myanmar' },
        { ID: 142, abbrev: 'MNE', country: 'Montenegro' },
        { ID: 143, abbrev: 'MNG', country: 'Mongolia' },
        { ID: 144, abbrev: 'MNP', country: 'Northern Mariana Islands' },
        { ID: 145, abbrev: 'MOZ', country: 'Mozambique' },
        { ID: 146, abbrev: 'MRT', country: 'Mauritania' },
        { ID: 147, abbrev: 'MSR', country: 'Montserrat' },
        { ID: 242, abbrev: 'MTQ', country: 'Martinique' },
        { ID: 148, abbrev: 'MUS', country: 'Mauritius' },
        { ID: 149, abbrev: 'MWI', country: 'Malawi' },
        { ID: 150, abbrev: 'MYS', country: 'Malaysia' },
        { ID: 243, abbrev: 'MYT', country: 'Mayotte' },
        { ID: 151, abbrev: 'NAM', country: 'Namibia' },
        { ID: 152, abbrev: 'NCL', country: 'New Caledonia' },
        { ID: 153, abbrev: 'NER', country: 'Niger' },
        { ID: 154, abbrev: 'NFK', country: 'Norfolk Island' },
        { ID: 155, abbrev: 'NGA', country: 'Nigeria' },
        { ID: 156, abbrev: 'NIC', country: 'Nicaragua' },
        { ID: 157, abbrev: 'NIU', country: 'Niue' },
        { ID: 158, abbrev: 'NLD', country: 'Netherlands' },
        { ID: 245, abbrev: 'NOR', country: 'Norway' },
        { ID: 159, abbrev: 'NPL', country: 'Nepal' },
        { ID: 160, abbrev: 'NRU', country: 'Nauru' },
        { ID: 161, abbrev: 'NZL', country: 'New Zealand' },
        { ID: 162, abbrev: 'OMN', country: 'Oman' },
        { ID: 163, abbrev: 'PAK', country: 'Pakistan' },
        { ID: 164, abbrev: 'PAN', country: 'Panama' },
        { ID: 165, abbrev: 'PCN', country: 'Pitcairn Islands' },
        { ID: 166, abbrev: 'PER', country: 'Peru' },
        { ID: 167, abbrev: 'PHL', country: 'Philippines' },
        { ID: 168, abbrev: 'PLW', country: 'Palau' },
        { ID: 169, abbrev: 'PNG', country: 'Papua New Guinea' },
        { ID: 170, abbrev: 'POL', country: 'Poland' },
        { ID: 171, abbrev: 'PRI', country: 'Puerto Rico' },
        { ID: 172, abbrev: 'PRK', country: 'Dem. Rep. Korea' },
        { ID: 173, abbrev: 'PRT', country: 'Portugal' },
        { ID: 174, abbrev: 'PRY', country: 'Paraguay' },
        { ID: 175, abbrev: 'PSE', country: 'Palestine' },
        { ID: 176, abbrev: 'PYF', country: 'French Polynesia' },
        { ID: 177, abbrev: 'QAT', country: 'Qatar' },
        { ID: 244, abbrev: 'REU', country: 'Reunion' },
        { ID: 178, abbrev: 'ROU', country: 'Romania' },
        { ID: 179, abbrev: 'RUS', country: 'Russian Federation' },
        { ID: 180, abbrev: 'RWA', country: 'Rwanda' },
        { ID: 182, abbrev: 'SAU', country: 'Saudi Arabia' },
        { ID: 183, abbrev: 'SDN', country: 'Sudan' },
        { ID: 185, abbrev: 'SEN', country: 'Senegal' },
        { ID: 186, abbrev: 'SGP', country: 'Singapore' },
        { ID: 187, abbrev: 'SGS', country: 'South Georgia and South Sandwich Islands' },
        { ID: 188, abbrev: 'SHN', country: 'Saint Helena' },
        { ID: 246, abbrev: 'SJM', country: 'Svalbard and Jan Mayen' },
        { ID: 189, abbrev: 'SLB', country: 'Solomon Islands' },
        { ID: 190, abbrev: 'SLE', country: 'Sierra Leone' },
        { ID: 191, abbrev: 'SLV', country: 'El Salvador' },
        { ID: 192, abbrev: 'SMR', country: 'San Marino' },
        { ID: 194, abbrev: 'SOM', country: 'Somalia' },
        { ID: 195, abbrev: 'SPM', country: 'Saint Pierre and Miquelon' },
        { ID: 196, abbrev: 'SRB', country: 'Serbia' },
        { ID: 184, abbrev: 'SSD', country: 'South Sudan' },
        { ID: 197, abbrev: 'STP', country: 'Sao Tome and Principe' },
        { ID: 198, abbrev: 'SUR', country: 'Suriname' },
        { ID: 199, abbrev: 'SVK', country: 'Slovakia' },
        { ID: 200, abbrev: 'SVN', country: 'Slovenia' },
        { ID: 201, abbrev: 'SWE', country: 'Sweden' },
        { ID: 202, abbrev: 'SWZ', country: 'Swaziland' },
        { ID: 203, abbrev: 'SXM', country: 'Sint Maarten' },
        { ID: 204, abbrev: 'SYC', country: 'Seychelles' },
        { ID: 205, abbrev: 'SYR', country: 'Syria' },
        { ID: 206, abbrev: 'TCA', country: 'Turks and Caicos Islands' },
        { ID: 207, abbrev: 'TCD', country: 'Chad' },
        { ID: 208, abbrev: 'TGO', country: 'Togo' },
        { ID: 209, abbrev: 'THA', country: 'Thailand' },
        { ID: 210, abbrev: 'TJK', country: 'Tajikistan' },
        { ID: 211, abbrev: 'TKM', country: 'Turkmenistan' },
        { ID: 212, abbrev: 'TLS', country: 'Timor-Leste' },
        { ID: 213, abbrev: 'TON', country: 'Tonga' },
        { ID: 214, abbrev: 'TTO', country: 'Trinidad and Tobago' },
        { ID: 215, abbrev: 'TUN', country: 'Tunisia' },
        { ID: 216, abbrev: 'TUR', country: 'Turkey' },
        { ID: 217, abbrev: 'TUV', country: 'Tuvalu' },
        { ID: 218, abbrev: 'TWN', country: 'Taiwan' },
        { ID: 219, abbrev: 'TZA', country: 'Tanzania' },
        { ID: 220, abbrev: 'UGA', country: 'Uganda' },
        { ID: 221, abbrev: 'UKR', country: 'Ukraine' },
        { ID: 222, abbrev: 'UMI', country: 'United States Minor Outlying Islands' },
        { ID: 223, abbrev: 'URY', country: 'Uruguay' },
        { ID: 224, abbrev: 'USA', country: 'United States' },
        { ID: 225, abbrev: 'UZB', country: 'Uzbekistan' },
        { ID: 226, abbrev: 'VAT', country: 'Vatican' },
        { ID: 227, abbrev: 'VCT', country: 'Saint Vincent and the Grenadines' },
        { ID: 228, abbrev: 'VEN', country: 'Venezuela' },
        { ID: 229, abbrev: 'VGB', country: 'British Virgin Islands' },
        { ID: 230, abbrev: 'VIR', country: 'United States Virgin Islands' },
        { ID: 231, abbrev: 'VNM', country: 'Vietnam' },
        { ID: 232, abbrev: 'VUT', country: 'Vanuatu' },
        { ID: 233, abbrev: 'WLF', country: 'Wallis and Futuna Islands' },
        { ID: 234, abbrev: 'WSM', country: 'Samoa' },
        { ID: 235, abbrev: 'YEM', country: 'Yemen' },
        { ID: 236, abbrev: 'ZAF', country: 'South Africa' },
        { ID: 237, abbrev: 'ZMB', country: 'Zambia' },
        { ID: 238, abbrev: 'ZWE', country: 'Zimbabwe' }
    ];